name: C++

on:
  push:
    branches: [ '**' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Lint Code Base
      uses: github/super-linter@v3
      env:
        VALIDATE_ALL_CODEBASE: true
        DEFAULT_BRANCH: develop
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        platformio-ci-src: [example/main.cpp]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: pio ci --board=nodemcu --board=nodemcuv2 --board=d1 --board=d1_mini
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.platformio-ci-src }}